//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnicoSITEB.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

||||||| parent of 4df7faf (ok)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
=======
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
>>>>>>> tapiaCode
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
>>>>>>> 4df7faf (ok)
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
<<<<<<< HEAD
||||||| parent of 4df7faf (ok)
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TAPIA-PC\\SQLEXPRESS;Initial Catalog=DBSITEP;Integrated Security=True")]
        public string DBSITEPConnectionString {
            get {
                return ((string)(this["DBSITEPConnectionString"]));
            }
        }
=======
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JHON-CRUZ;Initial Catalog=DBSITEP;Integrated Security=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TAPIA-PC\\SQLEXPRESS;Initial Catalog=DBSITEP;Integrated Security=True")]
>>>>>>> tapiaCode
        public string DBSITEPConnectionString {
            get {
                return ((string)(this["DBSITEPConnectionString"]));
            }
        }
>>>>>>> 4df7faf (ok)
    }
}
