//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnicoSITEB.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha_Garantia { get; set; }
        public Nullable<double> Precio_compra { get; set; }
        public long IdPedido { get; set; }
        public long IdPrecio { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Precio Precio { get; set; }
    }
}
