//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnicoSITEB.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSITEPEntities : DbContext
    {
        public DBSITEPEntities()
            : base("name=DBSITEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barrio> Barrio { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual DbSet<Ejemplar> Ejemplar { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<inicio_sesion> inicio_sesion { get; set; }
        public virtual DbSet<Juridico> Juridico { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Monitoreo> Monitoreo { get; set; }
        public virtual DbSet<Natural> Natural { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rubro> Rubro { get; set; }
        public virtual DbSet<Sub_Categoria> Sub_Categoria { get; set; }
        public virtual DbSet<Zona> Zona { get; set; }
        public virtual DbSet<VistaEmpleadoCargo> VistaEmpleadoCargo { get; set; }
    }
}
